### ISSUE TITLE
Get Started Help

### ISSUE THREAD

**Issue by MinZe25** [swagger-akka-http/swagger-scala-module#115]
Hello, I have a scala 2.11 sbt project and I want to add swagger but I can't find a way to make it work without adding a framework. (I would prefer not to use a framework).
Do you have a get started guide? 
Thanks!!

**Comment by pjfanning** [comment]
Including this jar on your classpath is enough to enable it - this is enabled by this file in the jar - https://github.com/swagger-akka-http/swagger-scala-module/blob/develop/src/main/resources/META-INF/services/io.swagger.v3.core.converter.ModelConverter

https://github.com/swagger-akka-http/swagger-akka-http/blob/master/src/main/scala/com/github/swagger/akka/SwaggerHttpService.scala#L59 will give you an idea of the code needed to generate an OpenAPI specification.

**Comment by MinZe25** [comment]
Thanks!! I will give it a try and give feedback as soon as possible :)
