### ISSUE TITLE
Reflection issue since the version 2.7.3

### ISSUE THREAD

**Issue by VincentBrule** [swagger-akka-http/swagger-scala-module#192]
Hello,
Since the version 2.7.3, I'm getting this error: `java.lang.NoClassDefFoundError: no Java class corresponding to T found`
I tried to create an example as minimal as possible to reproduce the error:

```
final case class DataExampleClass(
    data: CustomCollection[ExampleProperties]
)

final case class CustomCollection[T](
    features: Seq[FeatureExample[T]]
)

final case class FeatureExample[T](
    geometry: Option[T]
)

final case class ExampleProperties(
    p1: Int,
    p2: Double
)
```
And:
```
@Path(Example)
trait ExampleRoutesSwagger {

  @Path(Paths.Slash)
  @GET
  @Operation(
    summary = "",
    responses = Array(
      new ApiResponse(
        responseCode = "200",
        description  = "",
        content = Array(
          new Content(
            mediaType = MediaType.APPLICATION_JSON,
            array = new ArraySchema(
              schema = new Schema(
                implementation = classOf[DataExampleClass],
                required       = true
              )
            )
          )
        )
      ),
    )
  )
  def getAll: Route
}

```

With this, you can easily reproduce the bug normally.

Do you have an idea what can be the issue? I also tried with the latest code of develop.

**Comment by pjfanning** [comment]
I'm not sure how easy this is going to be to get working.

You could rewrite your classes - something like:
```
final case class DataExampleClass(
    data: CustomCollectionExampleProperties
)

final case class CustomCollectionExampleProperties(
    features: Seq[FeatureExampleProperties]
)

final case class FeatureExampleProperties(
    geometry: Option[ExampleProperties]
)
```

**Comment by pjfanning** [comment]
I have a PR that fixes the issue. Could you stick with swagger-scala-module v2.7.2? I don't plan to do a new release for a few weeks - until after Jackson v2.14.0 comes out.

**Comment by VincentBrule** [comment]
Yes sure no problem, I will stick with v2.7.2 until the new version is released. Thanks for your help and your quick answer @pjfanning 🙏

**Comment by pjfanning** [comment]
I released v2.7.5 with this fix, the scala 3 support has some extra experimental changes but the scala 2 builds should be safe to use.

**Comment by pjfanning** [comment]
@SamTheisens the v2.7.5 releases has some fixes, would you be able to try it out?

**Comment by VincentBrule** [comment]
Sorry for the delay @pjfanning, this specific issue is gone with the latest release, thanks.

**Comment by SamTheisens** [comment]
> @SamTheisens the v2.7.5 releases has some fixes, would you be able to try it out?

Sorry, haven't tried this out yet. Will get back to you if I encounter any issues

**Comment by SamTheisens** [comment]
@pjfanning I found one issue. Here's a fix: https://github.com/swagger-akka-http/swagger-scala-module/pull/206
